/*******************************************************************************
 * FILE:         trig.h
 * MODULE:       Core/Math
 * DESCRIPTION:  Trigonometric function approximations for the PSX runtime
 *               via precomputed lookup tables (LUTs). There is no FPU and no
 *               libm on the target hardware. All sin/cos results are returned
 *               as FP4_12 fixed-point values.
 *
 *               ANGLE SYSTEM — Binary Angular Measurement (BAM8):
 *                 Angles are represented as uint8_t values in the range 0-255.
 *                 This maps the full circle (0 to 2*PI) to exactly 256 steps.
 *                 0   = 0 degrees   (east / positive X axis)
 *                 64  = 90 degrees  (north / positive Y axis)
 *                 128 = 180 degrees (west / negative X axis)
 *                 192 = 270 degrees (south / negative Y axis)
 *                 255 = 358.59 degrees (just before 360)
 *
 *               WHY 256 STEPS?
 *                 - A uint8_t naturally wraps from 255 back to 0, which means
 *                   angle arithmetic (add, subtract) is automatically modular
 *                   with no bounds checking required. Angle overflow is free.
 *                 - 256 entries fit entirely in the 1KB Scratchpad if needed.
 *                 - The PSX GTE's own rotation-angle representation (rxy, ryz)
 *                   uses a similar BAM-like scheme, so this aligns naturally.
 *
 *               LUT FORMAT:
 *                 sin_lut[i] = (int16_t)(sin(i * 2*PI / 256) * 4096)
 *                 Values are in FP4_12 format (scale = 4096 = FP4_12_ONE).
 *                 Range: -4096 to +4096, stored as signed 16-bit integers.
 *                 The table fits in 512 bytes (256 * 2). Cosine is derived
 *                 via phase offset — no separate cos table needed.
 *
 * DEPENDENCIES: fixed.h
 *******************************************************************************/

#ifndef PSX_TRIG_H
#define PSX_TRIG_H

#include <stdint.h>
#include "fixed.h"

/* ---------------------------------------------------------------------------
 * Angle type alias.
 * Use BAM8 everywhere an angle is passed to make intent clear at call sites.
 * BAM8 arithmetic wraps automatically — (BAM8)255 + (BAM8)1 == (BAM8)0.
 * --------------------------------------------------------------------------- */

typedef uint8_t BAM8;

/* ---------------------------------------------------------------------------
 * Pre-computed 256-entry sine lookup table.
 * Values are FP4_12 (scale 4096). Range [-4096, +4096].
 *
 * Generated by: round(sin(i * 2 * PI / 256) * 4096) for i in [0, 255].
 * Stored as int16_t to minimize the table's footprint in ROM/RAM.
 *
 * The table is declared extern here and defined once in trig.c so that
 * the linker places exactly one copy in the binary regardless of how many
 * translation units include this header.
 * --------------------------------------------------------------------------- */

extern const int16_t psx_sin_lut[256];

/* ---------------------------------------------------------------------------
 * FP_Sin — Return the sine of an angle as FP4_12.
 *
 * This is an inline accessor — the compiler will inline the array index and
 * sign-extension to int32_t, producing a single LHU + SEB or equivalent
 * load sequence. No function call overhead.
 *
 * @param angle  BAM8 angle (0-255, full circle = 256 steps)
 * @return       FP4_12 result in range [-4096, +4096]
 * --------------------------------------------------------------------------- */

static inline FP4_12 FP_Sin(BAM8 angle)
{
    /* Cast to int32_t on load — the int16_t is sign-extended automatically.
     * The result is already in FP4_12 scale (multiply by FP4_12_ONE = 4096). */
    return (FP4_12)psx_sin_lut[angle];
}

/* ---------------------------------------------------------------------------
 * FP_Cos — Return the cosine of an angle as FP4_12.
 *
 * cos(theta) == sin(theta + 90 degrees).
 * In BAM8, 90 degrees == 64.
 * Adding 64 to a uint8_t wraps naturally at 256 — no branching, no masking.
 *
 * @param angle  BAM8 angle
 * @return       FP4_12 result in range [-4096, +4096]
 * --------------------------------------------------------------------------- */

static inline FP4_12 FP_Cos(BAM8 angle)
{
    /* Phase-shift by 64 BAM8 units = 90 degrees.
     * The uint8_t addition wraps modulo 256 automatically. */
    return (FP4_12)psx_sin_lut[(uint8_t)(angle + 64u)];
}

/* ---------------------------------------------------------------------------
 * FP_SinCos — Compute both sin and cos simultaneously.
 *
 * When you need both (e.g., building a rotation matrix row), calling this
 * once vs. calling FP_Sin + FP_Cos separately avoids a redundant index
 * calculation. The compiler can schedule both loads from the LUT together.
 *
 * @param angle  BAM8 angle
 * @param s_out  Output pointer for sin result (FP4_12)
 * @param c_out  Output pointer for cos result (FP4_12)
 * --------------------------------------------------------------------------- */

static inline void FP_SinCos(BAM8 angle, FP4_12 *s_out, FP4_12 *c_out)
{
    *s_out = (FP4_12)psx_sin_lut[angle];
    *c_out = (FP4_12)psx_sin_lut[(uint8_t)(angle + 64u)];
}

/* ---------------------------------------------------------------------------
 * Angle Construction Helpers
 * Convert from common human units to BAM8.
 * These are integer-only and intentionally lose sub-step precision —
 * that is acceptable because BAM8 is a 1.40625-degree-per-step system.
 * --------------------------------------------------------------------------- */

/* Convert integer degrees (0-359) to BAM8.
 * Multiply by 256 then divide by 360. No floating point. */
#define DEG_TO_BAM8(deg)    ((BAM8)(((uint32_t)(deg) * 256u) / 360u))

/* Convert BAM8 back to integer degrees (approximate, truncates). */
#define BAM8_TO_DEG(bam)    ((uint32_t)((uint32_t)(bam) * 360u) / 256u)

#endif /* PSX_TRIG_H */
